# Generated by Django 3.0.3 on 2020-02-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
